connector.name=iceberg
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=http://lakekeeper:8181/catalog
iceberg.rest-catalog.warehouse=my_warehouse
iceberg.rest-catalog.security=NONE

fs.native-s3.enabled=true
s3.endpoint=http://garage:3900
s3.region=garage
s3.path-style-access=true
s3.aws-access-key=${ENV:GARAGE_ACCESS_KEY_ID}
s3.aws-secret-key=${ENV:GARAGE_SECRET_ACCESS_KEY}
